spring.application.name=transport-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.zqbpbdnlxiazdnblamja
spring.datasource.password=TransportDatabase8825*

admin.email=karthi@admin.org
admin.password=karthi1234*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.datasource.hikari.data-source-properties.prepareThreshold=0

server.port=${PORT:8080}